ifeq ($(subdir),string)
sysdep_routines += memcpy_generic memcpy_thunderx memcpy_thunderx2 \
		   memcpy_falkor memcpy_a64fx \
		   memmove_falkor memset_generic memset_falkor \
		   memset_a64fx
endif
